### ISSUE TITLE
Specifying a custom dir with "dirCircuits"

### ISSUE THREAD

**Issue by cedoor** [erhant/circomkit#33] opened 2023-11-28 17:57 UTC
If I specify a custom directory for my circuit templates (e.g. src) and run `circomkit compile` it still creates a `circuits/main/circuit.circom` folder for its component. It fails because the relative path generated within that circuit is wrong. `"../circuit.circom"` doesn't exist in that folder.

I think the right folder for components should be `src/main/circuit.circom`.

The following line could be the problem. 

https://github.com/erhant/circomkit/blob/0473d8859ff27cb01eb530a9d8887f411a2d8425/src/utils/instantiate.ts#L42

Does it make sense? Or am I missing something?

**Comment by erhant** [comment] 2023-11-28 20:26
Hello, thanks for the issue!

You are right, I believe I'd initially started as an opinionated repo where all circuits lay below `circuits` folder but then I added the configs, apparently forgot to connect this particular setting to instantiate.

There is a [test](https://github.com/erhant/circomkit/blob/main/tests/circomkit.test.ts#L95) for a custom path but there is no test for custom dir, so I think I will add a test for this as well. 

I will fix it by exposing that directory config to instantiate + use that for `targetDir`. Probably tomorrow 🙏🏻 
I will `@` you when new version is published to NPM.

**Comment by cedoor** [comment] 2023-11-28 21:23
@erhant Thanks for your quick reply, I'll wait for it. And great work, I like really this tool!

**Comment by erhant** [comment] 2023-11-29 15:34
@cedoor heya, I believe the issue is fixed now & is published at v0.0.19

The test workflow failed because apparently the Circom installation fails in the workflow (#35 ) but the tests were passing locally™ for me. Please let me know if the issue is fixed on your end.

Also I wanted to ask for an opinion: the fix is as we have first discussed where Circomkit has a single `dirCircuits` and expects all circuits to be under there, and the rest of the path should be made via the `file` field of a circuit config. Would it make sense to also have an optional `dirCircuits`-like field for each circuit?

**Comment by cedoor** [comment] 2023-11-29 16:27
@erhant It works 👍🏽 Thank you so much!

> Also I wanted to ask for an opinion: the fix is as we have first discussed where Circomkit has a single dirCircuits and expects all circuits to be under there, and the rest of the path should be made via the file field of a circuit config. Would it make sense to also have an optional dirCircuits-like field for each circuit?

Yes, I think it makes sense and I'd probably need it soon :D

**Comment by erhant** [comment] 2023-11-29 16:51
No problem! 

Truly happy to hear that you enjoyed the lib & a pleasure to see PSE using it ❤️ 

I've created an issue about the aforementioned feature #37, I will look at it sometime soon, please `@` me in that issue if you happen to need that urgently 👍🏻

**Closed by erhant** 2023-11-29 16:51 UTC
Labels: bug

**Comment by cedoor** [comment] 2023-11-29 17:07
> I've created an issue about the aforementioned feature #37, I will look at it sometime soon, please `@` me in that issue if you happen to need that urgently 👍🏻

Sure! I think it's not urgent tho :)
